package ExceptionPrachiMam;

public class Ex2 {
	public static void main(String[] args) {//testing each block individually
		//try{
			double d=15/0;
			System.out.println(d);
	//	}catch(ArithmeticException e){
		//	System.out.println("Number cannot be divided by zero");
		//}finally{
			//System.out.println("Finally attempted");
		}
	}

//}
